name: Weekly Poll Bot

on:
  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: "45 10 * * 5"

jobs:
  run-weekly-poll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Check Node.js version
        run: node --version
    
      - name: Install dependencies
        run: npm install

      - name: Run the Telegram bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "Setting up bot environment..."
          export BOT_TOKEN=$BOT_TOKEN
          export CHAT_ID=$CHAT_ID
          node index.js
